services:
#    oc_platform.example:
#        class: OCPlatformBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    oc_platform.antispam:
        class: OC\PlatformBundle\Antispam\OCAntispam
        public: true
        arguments:
            - "@mailer"
            - %locale%
            - 50